/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gildedrose

import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class GuildedRoseTest {

//    val items = listOf(
//        Item(name="+5 Dexterity Vest", sellInDays = 10, quality = 20),
//        Item(name="Aged Brie", sellInDays = 2, quality = 0),
//        Item(name="Elixir of the Mongoose", sellInDays = 5, quality = 7),
//        Item(name="Sulfuras, Hand of Ragnaros", sellInDays = 0, quality = 80),
//        Item(name="Backstage passes to a TAFKAL80ETC concert", sellInDays = 15, quality = 20),
//        Item(name="Conjured Mana Cake", sellInDays = 3, quality = 6),
//    )

    var rose = GuildedRose()
    @BeforeTest
    fun updateQuality() {
        rose = GuildedRose()
        rose.updateQuality()
    }

    @Test
    fun `sulfuras cost always 80`() {
        assertEquals(80, rose.items.first { it.name == "Sulfuras, Hand of Ragnaros" }.quality)
    }

    @Test
    fun `quality is never negative`() {
        rose.items.forEach {
            assertTrue( it.quality > 0)
        }
    }

    @Test
    fun `elixir reduces both values by one`() {
        assertEquals(6, rose.items.name("Elixir of the Mongoose").quality )
        assertEquals(4, rose.items.name("Elixir of the Mongoose").sellInDays )
    }

    @Test
    fun `Vest quality decreases twice as fast after sellInDays`() {
        assertEquals(19, rose.items.name("+5 Dexterity Vest").quality )
        assertEquals(9, rose.items.name("+5 Dexterity Vest").sellInDays )
        for (times in 1..10) {
            rose.updateQuality()
        }
        assertEquals(8, rose.items.name("+5 Dexterity Vest").quality )
        assertEquals(-1, rose.items.name("+5 Dexterity Vest").sellInDays )
    }

    @Test
    fun `Aged Brie increases in quality the older it gets`() {
        assertEquals(1, rose.items.name("Aged Brie").sellInDays )
        assertEquals(1, rose.items.name("Aged Brie").quality )

        rose.updateQuality()
        assertEquals(0, rose.items.name("Aged Brie").sellInDays )
        assertEquals(2, rose.items.name("Aged Brie").quality )
        rose.updateQuality()
        assertEquals(-1, rose.items.name("Aged Brie").sellInDays )
        assertEquals(4, rose.items.name("Aged Brie").quality )
    }

    @Test
    fun `Quality never more than 50`(){
        for (times in 1..100) {
            rose.updateQuality()
        }
        rose.items.forEach {
            assertTrue(it.quality <= 50 || it.name == "Sulfuras, Hand of Ragnaros")
        }
    }
    
    @Test
    fun `Backstage passes get more then less valuable`() {
        // Item(name="Backstage passes to a TAFKAL80ETC concert", sellInDays = 15, quality = 20),
        assertEquals(14, rose.items.name("Backstage passes to a TAFKAL80ETC concert").sellInDays )
        assertEquals(21, rose.items.name("Backstage passes to a TAFKAL80ETC concert").quality )
        for (times in 1..5) {rose.updateQuality()}
        assertEquals(9, rose.items.name("Backstage passes to a TAFKAL80ETC concert").sellInDays )
        assertEquals(27, rose.items.name("Backstage passes to a TAFKAL80ETC concert").quality )
        for (times in 1..5) {rose.updateQuality()}
        assertEquals(4, rose.items.name("Backstage passes to a TAFKAL80ETC concert").sellInDays )
        assertEquals(38, rose.items.name("Backstage passes to a TAFKAL80ETC concert").quality )
        for (times in 1..5) {rose.updateQuality()}
        assertEquals(-1, rose.items.name("Backstage passes to a TAFKAL80ETC concert").sellInDays )
        assertEquals(0, rose.items.name("Backstage passes to a TAFKAL80ETC concert").quality )
    }
}
