/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gildedrose

import kotlin.test.Test

class GuildedRoseTest {
    @Test fun `rose items decrease in quality`() {
        val rose = GuildedRose()
        rose.updateQuality()
    }
}
